package main

import (
	"wecode.sorint.it/opensource/papagaio-api/cmd"

	_ "github.com/swaggo/files" // swagger embed files

	_ "wecode.sorint.it/opensource/papagaio-api/docs" // docs is generated by Swag CLI, you have to import it.
)

// @BasePath /api

// @securitydefinitions.oauth2.password OAuth2Password
// @tokenUrl https://login.sorintdev.it/auth/realms/sorinttest/protocol/openid-connect/token
// @in header
// @name Authorization
func main() {
	cmd.Execute()
}
