package main

import (
	_ "github.com/swaggo/files" // swagger embed files

	"wecode.sorint.it/opensource/papagaio-api/cmd"
	_ "wecode.sorint.it/opensource/papagaio-api/docs" // docs is generated by Swag CLI, you have to import it.
)

var version = "0.0.1"

// @BasePath /api
// @host papagaio-api.sorintdev.it

// @securitydefinitions.oauth2.password OAuth2Password
// @tokenUrl https://login.sorintdev.it/auth/realms/sorinttest/protocol/openid-connect/token
// @in header
// @name Authorization
func main() {
	cmd.Execute()
}
