// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addexternaluser/{organizationRef}": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Add an external user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Add External User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organizationRef",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "external user email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.Organization"
                        }
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            }
        },
        "/agolarefs": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Return the organization ref list existing in Agola but not in Papagaio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Return the organization ref list",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        },
        "/createorganization": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create an organization in Papagaio and in Agola. If already exists on Agola and you want to use the same organization then use the query parameter force",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Create a new Organization in Papagaio/Agola",
                "parameters": [
                    {
                        "type": "string",
                        "description": "?force",
                        "name": "force",
                        "in": "query"
                    },
                    {
                        "description": "Organization information",
                        "name": "organization",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrganizationRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrganizationResponseDto"
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        },
        "/deleteexternaluser/{organizationRef}": {
            "delete": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete an external user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Delete External User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organizationRef",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "external user email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.Organization"
                        }
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            }
        },
        "/deleteorganization{organizationRef}": {
            "delete": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete an organization in Papagaio and in Agola. Its possible to delete only in Papagaio using the parameter internalonly.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Delete Organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization Name",
                        "name": "organizationRef",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "?internalonly",
                        "name": "internalonly",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.Organization"
                        }
                    },
                    "500": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/gettriggersconfig": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get trigger timers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triggers"
                ],
                "summary": "Return time triggers",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ConfigTriggersDto"
                            }
                        }
                    }
                }
            }
        },
        "/gitorganizations/{gitSourceName}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Return a list of all Organizations by GitSource",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitSources"
                ],
                "summary": "List Git Organizations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Git Source Name",
                        "name": "gitSourceName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.GitSource"
                        }
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            }
        },
        "/gitsource": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Add a GitSource with the data provided in the body",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitSources"
                ],
                "summary": "Add a GitSource",
                "parameters": [
                    {
                        "description": "Git Source information",
                        "name": "gitSource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GitSource"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.GitSource"
                        }
                    },
                    "422": {
                        "description": "Already exists"
                    }
                }
            }
        },
        "/gitsource/{gitSourceName}": {
            "put": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update GitSource information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitSources"
                ],
                "summary": "Update a GitSource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Git Source Name",
                        "name": "gitSourceName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.GitSource"
                        }
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Remove a GitSource",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitSources"
                ],
                "summary": "Remove a GitSource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Git Source Name",
                        "name": "gitSourceName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/model.GitSource"
                        }
                    },
                    "422": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/gitsources": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Return a list of gitsources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitSources"
                ],
                "summary": "Return a list of gitsources",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.GitSourcesDto"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        },
        "/report": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Obtain a full report of all organizations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Get Report",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.OrganizationDto"
                            }
                        }
                    }
                }
            }
        },
        "/report/{organizationRef}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Obtain a report of a specific organization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Get Report from a specific organization",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.OrganizationDto"
                            }
                        }
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            }
        },
        "/report/{organizationRef}/{projectName}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Obtain a report of a specific organization/project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Get Report from a specific organization/project",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.OrganizationDto"
                            }
                        }
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            }
        },
        "/savetriggersconfig": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Save trigger timers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triggers"
                ],
                "summary": "Save time triggers",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ConfigTriggersDto"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BranchDto": {
            "type": "object",
            "properties": {
                "lastFailedRunDate": {
                    "type": "string"
                },
                "lastFailedRunURL": {
                    "type": "string"
                },
                "lastRunDuration": {
                    "type": "integer"
                },
                "lastSuccessRunDate": {
                    "type": "string"
                },
                "lastSuccessRunURL": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "report": {
                    "$ref": "#/definitions/dto.ReportDto"
                },
                "state": {
                    "description": "state of last run",
                    "type": "string"
                }
            }
        },
        "dto.ConfigTriggersDto": {
            "type": "object",
            "properties": {
                "organizationsDefaultTriggerTime": {
                    "type": "integer"
                },
                "runFailedDefaultTriggerTime": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateOrganizationRequestDto": {
            "type": "object",
            "properties": {
                "agolaRef": {
                    "type": "string"
                },
                "behaviourExclude": {
                    "type": "string"
                },
                "behaviourInclude": {
                    "type": "string"
                },
                "behaviourType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "dto.CreateOrganizationResponseDto": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string"
                },
                "organizationURL": {
                    "type": "string"
                }
            }
        },
        "dto.GitSourcesDto": {
            "type": "object",
            "properties": {
                "gitApiUrl": {
                    "type": "string"
                },
                "loginUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.OrganizationDto": {
            "type": "object",
            "properties": {
                "agolaRef": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastFailedRunDate": {
                    "type": "string"
                },
                "lastFailedRunURL": {
                    "type": "string"
                },
                "lastRunDuration": {
                    "type": "integer"
                },
                "lastSuccessRunDate": {
                    "type": "string"
                },
                "lastSuccessRunURL": {
                    "type": "string"
                },
                "organizationName": {
                    "type": "string"
                },
                "organizationURL": {
                    "type": "string"
                },
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProjectDto"
                    }
                },
                "visibility": {
                    "type": "string"
                },
                "worstReport": {
                    "$ref": "#/definitions/dto.ReportDto"
                }
            }
        },
        "dto.ProjectDto": {
            "type": "object",
            "properties": {
                "branchs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BranchDto"
                    }
                },
                "projectName": {
                    "type": "string"
                },
                "projectURL": {
                    "type": "string"
                },
                "worstReport": {
                    "$ref": "#/definitions/dto.ReportDto"
                }
            }
        },
        "dto.ReportDto": {
            "type": "object",
            "properties": {
                "branchName": {
                    "type": "string"
                },
                "failedRuns": {
                    "type": "integer"
                },
                "organizationName": {
                    "type": "string"
                },
                "projectName": {
                    "type": "string"
                },
                "successRunsPercentage": {
                    "type": "integer"
                },
                "totalRuns": {
                    "type": "integer"
                }
            }
        },
        "model.Branch": {
            "type": "object",
            "properties": {
                "lastFailedRun": {
                    "$ref": "#/definitions/model.RunInfo"
                },
                "lastRuns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RunInfo"
                    }
                },
                "lastSuccessRun": {
                    "$ref": "#/definitions/model.RunInfo"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.GitSource": {
            "type": "object",
            "properties": {
                "agolaRemoteSource": {
                    "type": "string"
                },
                "gitApiUrl": {
                    "type": "string"
                },
                "gitClientId": {
                    "type": "string"
                },
                "gitSecret": {
                    "type": "string"
                },
                "gitType": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Organization": {
            "type": "object",
            "properties": {
                "agolaOrganizationRef": {
                    "type": "string",
                    "example": "TestDemo"
                },
                "behaviourExclude": {
                    "type": "string"
                },
                "behaviourInclude": {
                    "type": "string"
                },
                "behaviourType": {
                    "type": "string",
                    "example": "none"
                },
                "externalUsers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "gitSourceName": {
                    "type": "string",
                    "example": "wecodedev"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "TestDemo"
                },
                "projects": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/model.Project"
                    }
                },
                "userIdConnected": {
                    "type": "integer",
                    "example": 1
                },
                "userIdCreator": {
                    "type": "integer",
                    "example": 1
                },
                "visibility": {
                    "type": "string",
                    "example": "public"
                },
                "webHookId": {
                    "type": "integer"
                }
            }
        },
        "model.Project": {
            "type": "object",
            "properties": {
                "agolaProjectID": {
                    "type": "string"
                },
                "agolaProjectRef": {
                    "type": "string"
                },
                "archivied": {
                    "type": "boolean"
                },
                "branchs": {
                    "description": "use branch name as key",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/model.Branch"
                    }
                },
                "gitRepoPath": {
                    "type": "string"
                }
            }
        },
        "model.RunInfo": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "runEndDate": {
                    "type": "string"
                },
                "runStartDate": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "https://login.sorintdev.it/auth/realms/sorinttest/protocol/openid-connect/token"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "papagaio-api.sorintdev.it",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
