basePath: /api
definitions:
  dto.BranchDto:
    properties:
      lastFailedRunDate:
        type: string
      lastFailedRunURL:
        type: string
      lastRunDuration:
        type: integer
      lastSuccessRunDate:
        type: string
      lastSuccessRunURL:
        type: string
      name:
        type: string
      report:
        $ref: '#/definitions/dto.ReportDto'
      state:
        description: state of last run
        type: string
    type: object
  dto.ConfigTriggersDto:
    properties:
      discoveryRunFailedTriggerLastRun:
        type: string
      organizationsTriggerLastRun:
        type: string
      organizationsTriggerTime:
        type: integer
      runFailedTriggerTime:
        type: integer
      usersTriggerLastRun:
        type: string
      usersTriggerTime:
        type: integer
    type: object
  dto.CreateOrganizationRequestDto:
    properties:
      agolaRef:
        type: string
      behaviourExclude:
        type: string
      behaviourInclude:
        type: string
      behaviourType:
        type: string
      name:
        type: string
      visibility:
        type: string
    type: object
  dto.CreateOrganizationResponseDto:
    properties:
      errorCode:
        type: string
      organizationURL:
        type: string
    type: object
  dto.GitSourcesDto:
    properties:
      gitApiUrl:
        type: string
      gitType:
        type: string
      loginUrl:
        type: string
      name:
        type: string
    type: object
  dto.OrganizationDto:
    properties:
      agolaRef:
        type: string
      avatarUrl:
        type: string
      id:
        type: string
      lastFailedRunDate:
        type: string
      lastFailedRunURL:
        type: string
      lastRunDuration:
        type: integer
      lastSuccessRunDate:
        type: string
      lastSuccessRunURL:
        type: string
      organizationName:
        type: string
      organizationURL:
        type: string
      projects:
        items:
          $ref: '#/definitions/dto.ProjectDto'
        type: array
      visibility:
        type: string
      worstReport:
        $ref: '#/definitions/dto.ReportDto'
    type: object
  dto.ProjectDto:
    properties:
      branchs:
        items:
          $ref: '#/definitions/dto.BranchDto'
        type: array
      projectName:
        type: string
      projectURL:
        type: string
      worstReport:
        $ref: '#/definitions/dto.ReportDto'
    type: object
  dto.ReportDto:
    properties:
      branchName:
        type: string
      failedRuns:
        type: integer
      organizationName:
        type: string
      projectName:
        type: string
      successRunsPercentage:
        type: integer
      totalRuns:
        type: integer
    type: object
  model.Branch:
    properties:
      lastFailedRun:
        $ref: '#/definitions/model.RunInfo'
      lastRuns:
        items:
          $ref: '#/definitions/model.RunInfo'
        type: array
      lastSuccessRun:
        $ref: '#/definitions/model.RunInfo'
      name:
        type: string
    type: object
  model.GitSource:
    properties:
      agolaRemoteSource:
        type: string
      gitApiUrl:
        type: string
      gitClientId:
        type: string
      gitSecret:
        type: string
      gitType:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  model.Organization:
    properties:
      agolaOrganizationRef:
        example: TestDemo
        type: string
      behaviourExclude:
        type: string
      behaviourInclude:
        type: string
      behaviourType:
        example: none
        type: string
      externalUsers:
        additionalProperties:
          type: boolean
        type: object
      gitName:
        example: TestDemo
        type: string
      gitOrganizationId:
        type: integer
      gitPath:
        example: TestDemo
        type: string
      gitSourceName:
        example: wecodedev
        type: string
      id:
        type: string
      projects:
        additionalProperties:
          $ref: '#/definitions/model.Project'
        type: object
      userIdConnected:
        example: 1
        type: integer
      userIdCreator:
        example: 1
        type: integer
      visibility:
        example: public
        type: string
      webHookId:
        type: integer
    type: object
  model.Project:
    properties:
      agolaProjectID:
        type: string
      agolaProjectRef:
        type: string
      archivied:
        type: boolean
      branchs:
        additionalProperties:
          $ref: '#/definitions/model.Branch'
        description: use branch name as key
        type: object
      gitRepoPath:
        type: string
    type: object
  model.RunInfo:
    properties:
      branch:
        type: string
      id:
        type: string
      phase:
        type: string
      result:
        type: string
      runEndDate:
        type: string
      runStartDate:
        type: string
    type: object
host: papagaio-api.sorintdev.it
info:
  contact: {}
paths:
  /addexternaluser/{organizationRef}:
    post:
      description: Add an external user
      parameters:
      - description: Organization name
        in: path
        name: organizationRef
        required: true
        type: string
      - description: external user email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.Organization'
        "404":
          description: not found
      security:
      - OAuth2Password: []
      summary: Add External User
      tags:
      - Organization
  /agolarefs:
    get:
      description: Return the organization ref list existing in Agola but not in Papagaio
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              type: string
            type: array
        "400":
          description: bad request
      security:
      - OAuth2Password: []
      summary: Return the organization ref list
      tags:
      - Organization
  /createorganization:
    post:
      description: Create an organization in Papagaio and in Agola. If already exists
        on Agola and you want to use the same organization then use the query parameter
        force
      parameters:
      - description: ?force
        in: query
        name: force
        type: string
      - description: Organization information
        in: body
        name: organization
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOrganizationRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/dto.CreateOrganizationResponseDto'
        "400":
          description: bad request
      security:
      - OAuth2Password: []
      summary: Create a new Organization in Papagaio/Agola
      tags:
      - Organization
  /deleteexternaluser/{organizationRef}:
    delete:
      description: Delete an external user
      parameters:
      - description: Organization name
        in: path
        name: organizationRef
        required: true
        type: string
      - description: external user email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.Organization'
        "404":
          description: not found
      security:
      - OAuth2Password: []
      summary: Delete External User
      tags:
      - Organization
  /deleteorganization{organizationRef}:
    delete:
      description: Delete an organization in Papagaio and in Agola. Its possible to
        delete only in Papagaio using the parameter internalonly.
      parameters:
      - description: Organization Name
        in: path
        name: organizationRef
        required: true
        type: string
      - description: ?internalonly
        in: query
        name: internalonly
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.Organization'
        "500":
          description: Not found
      security:
      - OAuth2Password: []
      summary: Delete Organization
      tags:
      - Organization
  /gettriggersconfig:
    get:
      description: Get trigger timers
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/dto.ConfigTriggersDto'
            type: array
      security:
      - OAuth2Password: []
      summary: Return time triggers
      tags:
      - Triggers
  /gitorganizations/{gitSourceName}:
    get:
      description: Return a list of all Organizations by GitSource
      parameters:
      - description: Git Source Name
        in: path
        name: gitSourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.GitSource'
        "404":
          description: not found
      security:
      - OAuth2Password: []
      summary: List Git Organizations
      tags:
      - GitSources
  /gitsource:
    post:
      description: Add a GitSource with the data provided in the body
      parameters:
      - description: Git Source information
        in: body
        name: gitSource
        required: true
        schema:
          $ref: '#/definitions/model.GitSource'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.GitSource'
        "422":
          description: Already exists
      security:
      - OAuth2Password: []
      summary: Add a GitSource
      tags:
      - GitSources
  /gitsource/{gitSourceName}:
    delete:
      description: Remove a GitSource
      parameters:
      - description: Git Source Name
        in: path
        name: gitSourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.GitSource'
        "422":
          description: Not found
      security:
      - OAuth2Password: []
      summary: Remove a GitSource
      tags:
      - GitSources
    put:
      description: Update GitSource information
      parameters:
      - description: Git Source Name
        in: path
        name: gitSourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/model.GitSource'
        "404":
          description: not found
      security:
      - OAuth2Password: []
      summary: Update a GitSource
      tags:
      - GitSources
  /gitsources:
    get:
      description: Return a list of gitsources
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/dto.GitSourcesDto'
            type: array
        "400":
          description: bad request
      security:
      - OAuth2Password: []
      summary: Return a list of gitsources
      tags:
      - GitSources
  /report:
    get:
      description: Obtain a full report of all organizations
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/dto.OrganizationDto'
            type: array
      security:
      - OAuth2Password: []
      summary: Get Report
      tags:
      - Organization
  /report/{organizationRef}:
    get:
      description: Obtain a report of a specific organization
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/dto.OrganizationDto'
            type: array
        "404":
          description: not found
      security:
      - OAuth2Password: []
      summary: Get Report from a specific organization
      tags:
      - Organization
  /report/{organizationRef}/{projectName}:
    get:
      description: Obtain a report of a specific organization/project
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/dto.OrganizationDto'
            type: array
        "404":
          description: not found
      security:
      - OAuth2Password: []
      summary: Get Report from a specific organization/project
      tags:
      - Organization
  /restarttriggers:
    post:
      description: Restartr timers
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - OAuth2Password: []
      summary: restart triggers
      tags:
      - Triggers
  /savetriggersconfig:
    post:
      description: Save trigger timers
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/dto.ConfigTriggersDto'
            type: array
      security:
      - OAuth2Password: []
      summary: Save time triggers
      tags:
      - Triggers
securityDefinitions:
  OAuth2Password:
    flow: password
    tokenUrl: https://login.sorintdev.it/auth/realms/sorinttest/protocol/openid-connect/token
    type: oauth2
swagger: "2.0"
